#version 460
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_integer_dot_product : require

layout(local_size_x = 1) in;

layout(set = 0, binding = 0, std430) buffer ResultBuffer {
    uint func1Result;
    uint func2Result;
} results;

layout(push_constant) uniform InputData {
    uint val;
} inputData;

uint32_t func1(uint32_t val) {
    const u8vec4 bits = unpack8(val);
    return bits.x + uint8_t(8) * bits.y;
}

uint32_t func2(uint32_t val) {
    return dotPacked4x8EXT(val, 0x00000801u);
}

void main() {
    results.func1Result = func1(inputData.val);
    results.func2Result = func2(inputData.val);
}