#version 460
#extension GL_EXT_shader_explicit_arithmetic_types : require
layout(local_size_x_id = 0) in;

layout (constant_id = 0) const uint SUBGROUP_SIZE = 16;
layout (constant_id = 1) const uint BM = 64;

struct InputElement {
    uint data;
    uint8_t value;
};

struct block_cache {
    int32_t qs[BM];
    float ds[SUBGROUP_SIZE];
};

shared block_cache buf[SUBGROUP_SIZE];

layout(set = 0, binding = 0, std430) readonly buffer InputBuffer {
    block_cache inputs[];
} inputBuffer;

layout(set = 0, binding = 1, std430) buffer ResultBuffer {
    uint8_t result[SUBGROUP_SIZE];
} results;

void main() {
    const uint index = gl_LocalInvocationID.x;

    for (uint offset = 0; offset < BM; ++offset) {
        buf[index].qs[offset] = inputBuffer.inputs[index].qs[offset];
    }
    for (uint offset = 0; offset < SUBGROUP_SIZE; ++offset) {
        buf[index].ds[offset] = inputBuffer.inputs[index].ds[offset];
    }

    barrier();

    float sum = 0.0;
    for (uint block = 0; block < SUBGROUP_SIZE; ++block) {
        sum += buf[block].ds[index];
    }
    results.result[index] = uint8_t(sum);
}